// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722161026_addedSeedingDataModelDiaryEntry")]
    partial class addedSeedingDataModelDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the content of the first diary entry.",
                            Creation = new DateTime(2025, 7, 22, 21, 40, 25, 569, DateTimeKind.Local).AddTicks(5820),
                            Title = "First Entry"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is the content of the second diary entry.",
                            Creation = new DateTime(2025, 7, 22, 21, 40, 25, 569, DateTimeKind.Local).AddTicks(6030),
                            Title = "Second Entry"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is the content of the third diary entry.",
                            Creation = new DateTime(2025, 7, 22, 21, 40, 25, 569, DateTimeKind.Local).AddTicks(6031),
                            Title = "Third Entry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
